spring.application.name=demo

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/personal_finance
spring.datasource.username=root
spring.datasource.password=swami@9945
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Boot Server
server.port=8081